# Generated by Django 3.2.9 on 2023-10-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('school_number', models.CharField(blank=True, max_length=256, null=True)),
                ('grade_number', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('subject1', models.CharField(blank=True, choices=[('math', 'Math'), ('english', 'English')], default='math', max_length=256, null=True)),
                ('subject1_score', models.IntegerField(blank=True, default=0, null=True)),
                ('subject2', models.CharField(blank=True, choices=[('math', 'Math'), ('english', 'English')], default='english', max_length=256, null=True)),
                ('subject2_score', models.IntegerField(blank=True, default=0, null=True)),
                ('language_code', models.CharField(blank=True, max_length=8, null=True)),
                ('is_blocked_bot', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
